/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;

/**
 *
 * @author Honza
 */
public class GameBoard extends javax.swing.JPanel
{

    BufferedImage map;
    BufferedImage topPanel;
    BufferedImage botPanel;

    public GameBoard()
    {
        initComponents();
        map = new BufferedImage(800, 800, BufferedImage.BITMASK);
        topPanel = new BufferedImage(800, 60, BufferedImage.BITMASK);
        botPanel = new BufferedImage(800, 100, BufferedImage.BITMASK);
    }

    @Override
    protected void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        Graphics gTopPanel = topPanel.createGraphics();
        gTopPanel.setColor(Color.white);
        gTopPanel.fillRect(0, 0, 800, 60);
        Graphics gBotPanel = botPanel.createGraphics();
        gBotPanel.setColor(Color.green);
        gBotPanel.fillRect(0, 0, 800, 100);

        Graphics gMap = map.createGraphics();
        gMap.setColor(Color.red);
        gMap.fillRect(0, 0, map.getWidth(), map.getHeight());
        gMap.setColor(Color.WHITE);
        gMap.drawImage(topPanel, 0, 0, null);
        gMap.setColor(Color.green);
        gMap.drawImage(botPanel, 0, 700, null);
        g.drawImage(map, 0, 0, null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
